name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    uses: hajle-silesia/app-test/.github/workflows/shared-image-build.yaml@master
    with:
      docker-hub-username: ${{ vars.DOCKER_HUB_USERNAME }}
      docker-hub-namespace: ${{ vars.DOCKER_HUB_NAMESPACE }}
    secrets:
      docker-hub-token: ${{ secrets.DOCKER_HUB_TOKEN }}

  chart-update:
    needs:
      - build
    name: Chart update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}-config
      - uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          message: ${{ github.event.head_commit.message }}
          token: ${{ secrets.PUSH_TOKEN }}
          changes: |
            {
              "charts/${{ github.event.repository.name }}/values.yaml": {
                "image.repository": "${{ needs.build.outputs.docker-hub-repository-name }}"
              },
              "charts/${{ github.event.repository.name }}/values.yaml": {
                "image.tag": "${{ needs.build.outputs.tag }}"
              },
              "charts/${{ github.event.repository.name }}/Chart.yaml": {
                "appVersion": "${{ needs.build.outputs.tag }}"
              }
            }
