name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    uses: hajle-silesia/.github/.github/workflows/shared-build.yaml@v1.2.0
    with:
      docker-hub-repository-name: mtweeman/hajle-silesia_app-test
    secrets:
      docker-hub-username: ${{ secrets.DOCKER_USER }}
      docker-hub-token: ${{ secrets.DOCKER_PASSWORD }}

  chart-update:
    needs:
      - build
    name: Chart update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: |
          pwd
          ls -la
          cd ..
          pwd
          ls -la
      - uses: fjogeleit/yaml-update-action@main
        with:
          repository: ${{ github.repository }}-config
          message: "Update image version to ${{ github.ref_name }}"
          token: ${{ secrets.PUSH_TOKEN }}
          changes: |
            {
              "charts/values.yaml": {
                "image.repository": "mtweeman/hajle-silesia_app-test"
              },
              "charts/values.yaml": {
                "image.tag": "${{ github.ref_name }}"
              }
            }
