name: Shared image build

on:
  workflow_call:
    inputs:
      docker-hub-username:
        description: Docker Hub username
        type: string
        required: true
      docker-hub-namespace:
        description: Docker Hub namespace
        type: string
        required: true
      dir:
        description: Directory containing Dockerfile
        type: string
        required: false
    secrets:
      docker-hub-token:
        description: Docker Hub token
        required: true
    outputs:
      docker-hub-repository-name:
        description: Docker Hub repository name
        value: ${{ jobs.shared-image-build.outputs.docker-hub-repository-name }}
      tag:
        description: Image tag
        value: ${{ jobs.shared-image-build.outputs.tag }}

permissions:
  contents: read

env:
  docker-hub-repository-name: ${{ inputs.docker-hub-namespace }}/${{ github.event.repository.name }}

jobs:
  shared-image-build:
    name: Shared image build
    runs-on: ubuntu-latest
    outputs:
      docker-hub-repository-name: ${{ env.docker-hub-repository-name }}
      tag: ${{ steps.meta.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.docker-hub-repository-name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=sha
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker-hub-username }}
          password: ${{ secrets.docker-hub-token }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.dir }}
          platforms: linux/amd64, linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
